name: Github CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🎉 Start
        run: echo "Triggered by ${{ github.event_name }} on branch ${{ github.ref }} in ${{ github.repository }}"

      # Check out your repo code
      - name: Check out repository code
        uses: actions/checkout@v5

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f week1/requirements.txt ]; then pip install -r week1/requirements.txt; fi
          # fallback: install common packages directly if requirements.txt is missing
          pip install matplotlib numpy networkx

      # Install Codon
      - name: Install Codon
        run: |
          mkdir -p ${HOME}/.codon
          curl -L https://github.com/exaloop/codon/releases/download/v0.19.3/codon-linux-x86_64.tar.gz \
            | tar zxvf - --strip-components=1 -C ${HOME}/.codon
          curl -L https://github.com/exaloop/seq/releases/download/v0.11.5/seq-linux-x86_64.tar.gz \
            | tar zxvf - -C ${HOME}/.codon/lib/codon/plugins
          echo "${HOME}/.codon/bin" >> $GITHUB_PATH

      # Set up Codon ↔ Python bridge
      - name: Set up Codon Python bridge
        run: |
          pip install find_libpython
          echo "CODON_PYTHON=$(python -c 'import find_libpython as f; print(f.find_libpython())')" >> $GITHUB_ENV
          echo "Found Python at: ${CODON_PYTHON}"

      - name: 🖥️ Run evaluation
        run: python week1/evaluate.py

